Python 3 / Ubuntu 18.04 support
obfuscurity/synthesize pull request #79
Opened 2020-02-17 17:31 UTC by deniszh

Quite crude attempt to migrate Synthesize to Python 3 / Ubuntu 18.04

TODO: Grafana dashboards and datasources setup needs to be migrated to provosioning API - https://grafana.com/docs/grafana/latest/administration/provisioning/

TODO: i used instance Systemd Instantiated units (https://serverfault.com/a/730339/104117), so, some logic needs to be added to loop over `INSTANCES` environment variables during install / uninstall / upgrade. Maybe that's not a best solution.

TODO: Tags are currenlty disabled in config, because current tagging code checking SSL certificates if any, so, bailing  out on snakeoil SSL certs.

I also removed python-openssl  warning, not sure if still relevant.

2020-02-22 23:51 UTC, obfuscurity requested changes
Really appreciate all your work on this one. I suspect some of my challenges were that I've been trying to hack on this in Windows Linux Subsystem and that's been a major hassle. If you're too busy just let me know and I can try to address the comments I left within.

I'm not sure if maintaining the `upgrade` script for this release even makes sense, what do you think?

2020-02-22 23:51 UTC, obfuscurity commented on install
> +    GRAPHITE_RELEASE='master'
Generally I prefer to default to the last known stable release, like we do for Vagrant. Mind switching his to 1.1.6?

2020-02-22 23:51 UTC, obfuscurity commented on install
> +    STATSITE_RELEASE='master'
Hmm, I was going to suggest a known stable release for statsite too but it looks like there hasn't been a release since 2016 with almost 200 commits, so I guess we'll stick with master here.

2020-02-22 23:51 UTC, obfuscurity commented on install
> +mkdir -p /etc/collectd
I don't think this is needed.

2020-02-22 23:51 UTC, obfuscurity commented on install
>  # Setup hourly cron to rebuild Graphite index
Do you think we should look at using systemd timers instead of cron?

2020-02-22 23:51 UTC, obfuscurity commented on install
> +apt-get install grafana
Add a space after this line?

2020-02-22 23:51 UTC, obfuscurity commented on install
> +
Remove this extra line?

2020-02-22 23:51 UTC, obfuscurity commented on templates/grafana/provisioning/dashboards/GraphiteCarbonMetrics_obfuscurity.json
> +          "target": "aliasByNode(scale(collectd.graphite.tail-graphite_web.response_time-retrieval_time_avg, 100), 3)"
This needs to be `min` instead of `avg`, would you mind fixing?

2020-02-22 23:51 UTC, obfuscurity commented on templates/grafana/provisioning/dashboards/GraphiteCarbonMetrics_obfuscurity.json
> +          "target": "aliasByNode(scaleToSeconds(collectd.graphite.interface-enp0s3.if_octets.*, 1), 4)"
Can we change this to:
`"target": "aliasByNode(scaleToSeconds(collectd.graphite.interface-*.if_octets.*, 1), 2, 4)"`

2020-02-22 23:51 UTC, obfuscurity commented on upgrade
> +# Synthesize upgrade script for Graphite 1.1.0
1.1.6

2020-02-23 11:41 UTC, deniszh commented on install
> +    GRAPHITE_RELEASE='master'
Ofc, was testing master. 1.1.7 will happen really soon btw.

2020-02-23 11:41 UTC, deniszh commented on install
> +    STATSITE_RELEASE='master'
Indeed. 🤷‍♂

2020-02-23 11:43 UTC, deniszh commented on install
> +mkdir -p /etc/collectd
I added it because ./uninstall && ./install failing otherwise, not sure why.

2020-02-23 11:46 UTC, deniszh commented on install
>  # Setup hourly cron to rebuild Graphite index
Ah, good idea. Let me do that.

2020-02-23 11:48 UTC, deniszh commented on install
> +apt-get install grafana
Done

2020-02-23 11:49 UTC, deniszh commented on install
> +
Done

2020-02-23 11:51 UTC, deniszh commented on templates/grafana/provisioning/dashboards/GraphiteCarbonMetrics_obfuscurity.json
> +          "target": "aliasByNode(scale(collectd.graphite.tail-graphite_web.response_time-retrieval_time_avg, 100), 3)"
I took it from https://grafana.com/grafana/dashboards/311
will fix it here

2020-02-23 11:51 UTC, deniszh commented on templates/grafana/provisioning/dashboards/GraphiteCarbonMetrics_obfuscurity.json
> +          "target": "aliasByNode(scaleToSeconds(collectd.graphite.interface-enp0s3.if_octets.*, 1), 4)"
Good idea

2020-02-23 11:51 UTC, deniszh commented on upgrade
> +# Synthesize upgrade script for Graphite 1.1.0
Done

2020-02-23 13:19 UTC, deniszh commented on install
> +mkdir -p /etc/collectd
Ah, I found an issue - uninstall was not uninstalling. Fixed.

2020-03-29 15:02 UTC, obfuscurity approved these changes

2020-03-29 15:03 UTC, deniszh commented
That was fast

2020-03-29 15:03 UTC, deniszh commented
Thanks, @obfuscurity !
Please merge if still have sense.

2020-03-29 15:04 UTC, obfuscurity approved these changes

2020-03-29 15:05 UTC, obfuscurity commented
> That was fast

I mean what else do I have to do sitting here on a Sunday morning watching the world burn?

2020-03-29 15:06 UTC, merged

2020-03-29 15:07 UTC, obfuscurity commented
Note that I haven't tested this yet but I've never known you to push broken code @deniszh. Thank you for this huge contribution. ❤️

2020-03-29 15:17 UTC, deniszh commented
Should work, just tested it with latest ubuntu 18.04 box (v20200325.0.0).
Take care, Jason! ❤️

2020-03-29 15:23 UTC, obfuscurity commented
I'll cut a new release as soon as I get a chance to play with it today.

2020-04-03 15:54 UTC, obfuscurity commented
Sorry for the delay. Tested master in a DO droplet and found one bug related to Statsite invocation. Pushed a fix, cutting a release soon.

2020-04-03 16:25 UTC, obfuscurity commented
https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0